-- vim.g.Illuminate_ftwhitelist = {
--   "vim",
--   "sh",
--   "python",
--   "lua",
--   "rust",
--   "typescriptreact",
--   "javascriptreact",
--   "typescript",
--   "javascript",
--   "terraform",
-- }
