require("plugins.nvimtree")
require("plugins.theme")
require("plugins.bufferline")
require("plugins.nerdcommenter")
require("plugins.sandwich")
-- require("plugins.galaxyline")
require("plugins.lualine")
require("plugins.blank-line")
require("plugins.treesitter")
require("plugins.matchup")
require("plugins.autopairs")
require("plugins.signs")
require("plugins.fzf")
require("plugins.neogit")
require("plugins.lastplace")
require("plugins.current-word")
require("plugins.formatter")
require("plugins.vimwiki")
require("plugins.diffview")
-- require("plugins.vim-dadbod-ui")
require("plugins.cmp")
require("plugins.terraform")
require("plugins.orgmode")
require("plugins.symbols-outline")

require("fzf_lsp").setup()
require("vgit").setup()
require("gitlinker").setup()
require("impatient").enable_profile()

-- require("plugins.null-ls")
-- require("plugins.lspfuzzy")
-- require("plugins.telescope")
-- require("navigator").setup()
-- require("plugins.nvim-lint")
-- require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
-- require("which-key").setup()
